server.port: 7001

#Mongo
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
#Logger
logging:
  level:
    root: INFO
    se.magnus: DEBUG

---
spring:
  profiles: docker

#Mongo
spring.data.mongodb.host: mongodb

server.port: 8080
